version: 2
jobs:
  backend:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo/backend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Configure backend
          command: |
            touch backend/config/default.json
            echo "HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL}" >> backend/config/default.json
            echo "HASURA_GRAPHQL_ENABLE_CONSOLE=false" >> backend/config/default.json
            echo "HASURA_GRAPHQL_ENABLED_LOG_TYPES=${HASURA_GRAPHQL_ENABLED_LOG_TYPES}" >> backend/config/default.json
            echo "HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}" >> backend/config/default.json
            echo "HASURA_GRAPHQL_JWT_SECRET={\"type\":\"HS256\", \"key\":\"${HASURA_GRAPHQL_JWT_SECRET}\"}"  >> backend/config/default.json

      - run:
          name: Install packages for backend
          command: |
            cd backend
            npm install
      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}

      # run tests!
      - run:
          name: Test backend
          command: |
            cd backend
            npm test
  frontend:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo/frontend

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "frontend/package.json" }}
            - v1-deps-

      - run:
          name: Install packages for frontend
          command: |
            cd frontend
            npm install
      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-deps-{{ checksum "frontend/package.json" }}

      - run:
          name: Build frontend
          command: |
            cd frontend
            npm build
workflows:
  version: 2
  back-front:
    jobs:
      - backend
      - frontend
